<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-01-23 20:53
=======
# Generated by Django 3.1.5 on 2021-01-23 21:45
>>>>>>> e1db5518752df2116b64c684750942a0926ddd50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='SupplyReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=30)),
                ('fullfilled', models.BooleanField(default=False)),
=======
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=30)),
>>>>>>> e1db5518752df2116b64c684750942a0926ddd50
                ('item_id', models.CharField(max_length=30)),
                ('item_amt', models.PositiveIntegerField()),
            ],
        ),
    ]
