# Generated by Django 3.1.5 on 2021-01-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=30)),
                ('item_id', models.CharField(max_length=30)),
                ('item_amt', models.PositiveIntegerField()),
            ],
        ),
    ]
