# Generated by Django 3.1.5 on 2021-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('camp_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('water', models.IntegerField(help_text='Water storage capacity', max_length=1)),
                ('food', models.IntegerField(help_text='Food storage capacity', max_length=1)),
                ('blanket', models.IntegerField(help_text='Blanket storage capacity', max_length=1)),
                ('drug', models.IntegerField(help_text='Drug storage capacity', max_length=1)),
            ],
        ),
    ]
