# Generated by Django 3.1.5 on 2021-01-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=30)),
                ('fullfilled', models.BooleanField(default=False)),
                ('item_id', models.CharField(max_length=30)),
                ('item_amt', models.PositiveIntegerField()),
            ],
        ),
    ]
